### ISSUE TITLE
Kolisionen der Map werden nicht geladen.

### ISSUE THREAD

**Issue by Selemba1000** [emign/engineEmi_Template#10]
[map.zip](https://github.com/emign/engineEmi_Template/files/4355876/map.zip)
Die Map enthält Kolisionen, die von einem Body nicht beachtet werden.

**Comment by emign** [comment]
Ja. Das ist so. Physic bodies reagieren nur untereinander. Du müsstest transparente bodies über die Strukturen an der map legen.
