### ISSUE TITLE
Auslesen der Map

### ISSUE THREAD

**Issue by Selemba1000** [emign/engineEmi_Template#11]
Wie kann man die Objekte der Map auslesen?
Das wäre wichtig um die Map mit Physik laden zu können. Mit dem Befehl *readTiledMap()* bekommt man zwar ein *TiledMap* Objekt, ich weiß jedoch nicht wie man dieses ausließt.

**Comment by emign** [comment]
Das muss man manuell machen. Box2D unterstützt das nicht von sich aus. Hier sind Tipps:
https://gamedev.stackexchange.com/questions/66924/how-can-i-convert-a-tilemap-to-a-box2d-world

**Comment by Selemba1000** [comment]
Der Link beschreibt den Code für libgdx, welcher mir jedoch bei dieser Engine nichts hilft.

**Comment by emign** [comment]
Ja. Dort sind "Tipps". Es gibt keine vorgefertigte Lösung. Libgdx verwendet auch Box2D. Näher wird man nicht kommen. Es gibt hier kein Copy/Paste
