### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by Selemba1000** [emign/engineEmi_Template#13]
Eine Frage:
Wie bekomme ich das Spielfenster auf Vollbildschirm ohne Topleiste und ohne weiße Streifen an den Rändern.

**Comment by Selemba1000** [comment]
Noch eine Frage:
Wie funktionieren relative Positions und Größen Angaben?

**Comment by emign** [comment]
In welchem Kontext ?

**Comment by Selemba1000** [comment]
Da die Größe des Fensters des Spiels von Gerät zu Gerät verschieden ist und sich das Fenster vergrößern und verkleinern lässt müssen sich auch die Größen und Positionen der Objekte verändern, um nicht essentielle Elemente zu verdecken, sodass sich das Spiel nur noch schwer oder gar nicht spielen lässt. Das Problem würde sich durch fullscreen zwar minimieren, doch die Größe von Bildschirmen kann auch stark variieren, sodass auch in diesem Fall die Objekte angepasst werden müssen. Durch ein Relatives Layout würden die Größen automatisch angepasst werden. Ferner noch müssen auch eventuell Texturen angepasst werden um schlechte Grafik oder Überlastung zu verhindern.

**Comment by emign** [comment]
Dafür verwendet man scaling. Jeder View kann mit .scale angepasst werden. 
Die Koordinaten passt du mit Faktoren an

**Comment by emign** [comment]
Echtes Fullscreen wird noch implemtentiert. v.0.60

**Comment by emign** [comment]
In 0.70 (extra branch derzeit noch) implementiert. Achtung: Teilweise geänderte Syntax

**Comment by emign** [comment]
Hast du 0.70+ schon getestet?

**Comment by Selemba1000** [comment]
Ja mache ich gerade, jedoch weiß ich aktuell nicht, was in die Main.kt rein muss um ein Module zu laden. Ein Sample mit einer neuen Version wäre nützlich.

**Comment by emign** [comment]
https://github.com/emign/engineEmi_Samples/tree/0.70?files=1

**Comment by Selemba1000** [comment]
In Version 0.77 funktioniert Fullscreen nicht.

**Comment by emign** [comment]
Ja ist ein Windows bug. macOS und Linux sollten gehen
