### ISSUE TITLE
Fehlende Variable für Spiele

### ISSUE THREAD

**Issue by Selemba1000** [emign/engineEmi_Template#5]
Eine delta time Variable fehlt.

**Comment by emign** [comment]
- Was soll die können?
- Wofür wird die benötigt?
- Welchen Datentyp soll sie haben?
- So viele Fragen...

**Comment by Selemba1000** [comment]
Eine Variable die die Zeit angibt die es gebraucht hat um den aktuellen Frame zu laden. Damit kann man das Movement von Objekten unabhängig von der Framerate machen, wenn man Kräfte verwendet.

**Comment by emign** [comment]
Kannst du mal ein Projekt hochladen, wo das relevant wird? In Box2D sollte ein verrechnen der DeltaTime nicht notwendig sein.

**Comment by Selemba1000** [comment]
[Test.zip](https://github.com/emign/engineEmi_Template/files/4287745/Test.zip)
Bei niedrigen Framerates wird die Bewegungsgeschwindigkeit unverhältnismäßig größer.

**Comment by emign** [comment]
Wie reproduzierst du die niedrigen Framerates? Ich habe keinerlei Einbrüche

**Comment by Selemba1000** [comment]
Linux open Local mit einem alten i3 und ohne Grafikkarte.

**Comment by emign** [comment]
Ohne das jetzt gesehen zu haben, schätze ich einfach, dass der Rechner an sich überfordert ist. 
Du startest immerhin 2 Coroutinen mit `while(true)` Schleifen, ohne Rücksicht auf bereits intern laufende Operationen.  Man müsste das mal am Gerät beruteilen

**Comment by Selemba1000** [comment]
Variable von Korge nennt sich Performance Counter und ist bereits vorhanden.
