### ISSUE TITLE
Fehler bei jsWebRun

### ISSUE THREAD

**Issue by Selemba1000** [emign/engineEmi_Template#6]
```
15:32:48: Executing task 'openInBrowser'...


> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :compileKotlinJs
> Task :genResources UP-TO-DATE
> Task :jsProcessResources
> Task :jsMainClasses
> Task :jsJar
> Task :jsWeb

> Task :jsWebRun
Listening (10812@DESKTOP-KRUI6H5-Thread[Execution worker for ':',5,main]) at http://0.0.0.0:59749/
15:33:35: Task execution finished 'openInBrowser'.
```
Die Webseite enthält die IP 0.0.0.0, welche nicht existiert.

**Comment by emign** [comment]
Du musst deine Fehlerberichte mit reproduzierbaren Anweisungen füttern, wie man sie erzeugt. So ist das leider nichts-sagend und sieht mir derzeit eher nach einer Fehlkonfiguration von IntelliJ aus

**Comment by Selemba1000** [comment]
Leeres Projekt frisch kopiert.

**Comment by emign** [comment]
0.0.0.0 beschreibt einfach alle die IP-Adressen des lokalen Rechners.
Wenn du Elemente anzeigen lässt, werden diese auch angezeigt.:
<img width="1153" alt="Game" src="https://user-images.githubusercontent.com/5278352/75890891-46a65080-5e2f-11ea-8ab4-449074de6d02.png">

Falls das unter Linux Probleme macht, versuche anstatt 0.0.0.0 127.0.0.1

**Comment by Selemba1000** [comment]
Macht auf Windows Probleme.
![Fehler](https://user-images.githubusercontent.com/60011459/75891219-bddbe480-5e2f-11ea-8464-e67852a5dffe.PNG)

**Comment by emign** [comment]
Bitte mit einem verbreiteteren Browser anstelle von Opera testen. Der Fehler ist bei Oper bekannt:

[-> Stackoverflow](https://superuser.com/questions/125047/opera-doesnt-recognize-0-0-0-0-as-localhost-is-this-behaviour-standard-conform)

**Comment by Selemba1000** [comment]
![Fehler_Edge](https://user-images.githubusercontent.com/60011459/75892064-047e0e80-5e31-11ea-87a8-7ead18df7725.PNG)
Hier nochmal der Fehler in Edge.

**Comment by emign** [comment]
Fixed with 
https://github.com/emign/engineEmi/commit/005e5ce7599ff797e1c4ee7471f4126813e16306
