### ISSUE TITLE
Map lädt nicht

### ISSUE THREAD

**Issue by Selemba1000** [emign/engineEmi_Template#7]
Die Beispiel-Map wird nicht geladen.
[Map.zip](https://github.com/emign/engineEmi_Template/files/4287996/Map.zip)
Kein Fehler wird ausgegeben.

**Comment by emign** [comment]
Das Problem liegt daran, dass die `Overworld.tsx` falsch formatiert ist. Das kann zum Beispiel beim Öffnen der Datei in Intellij passieren. Das wird in Version 0.45 behoben sein, die gerade hochlädt. Sample gibt es dann [hier](https://github.com/emign/engineEmi_Samples)
