### ISSUE TITLE
Engine lässt sich nicht importieren.

### ISSUE THREAD

**Issue by Selemba1000** [emign/engineEmi_Template#9]
import me.emig.engineEmi.* gibt einen unresolved-reference-Fehler aus.

**Comment by emign** [comment]
Bitte neu herunter laden oder in der Intellij Terminal Konsole:

`gradle wrapper --gradle-version=5.6.3`

**Comment by Selemba1000** [comment]
Neu heruntergeladen habe ich bereits und der befehl wird nicht erkannt.

**Comment by emign** [comment]
Welche gradle wrapper Version ?

**Comment by Selemba1000** [comment]
5.6.4-all

**Comment by emign** [comment]
Dann verwendet deine IDE nicht den wrapper. Bitte so konfigurieren dass der wrapper verwendet wird.

**Comment by Selemba1000** [comment]
Der wrapper wird verwendet jedoch bleibt der Fehler bestehen.

**Comment by emign** [comment]
Der Fehler ist Gradle 6.0+ spezifisch. Irgendwie wird bei dir noch eine andere Version verwendet.

Was steht hier:

<img width="1352" alt="Preferences_und_engineEmi_Template____dev_tmp_TestengineEmi_Template__-_____build_gradle__engineEmi_Template_" src="https://user-images.githubusercontent.com/5278352/76330880-a9479280-62ee-11ea-8458-16921d3bc3a0.png">

**Comment by Selemba1000** [comment]
'gradle-wrapper.properties' file

**Comment by emign** [comment]
was sagt `./gradle wrapper --gradle-version=5.6.3` (im intellij terminal eingegeben)

**Comment by Selemba1000** [comment]
Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Auf Windows heißt das glaube ich gradlew.

**Comment by emign** [comment]
_gradlew_ ist der wrapper
_gradle_ das normale gradle

**Comment by Selemba1000** [comment]
ach so.

**Comment by emign** [comment]
Ich testete gerade auf windows...
Funktioniert prächtig. Bitte mal dein Projekt zippen und schicken, dann kann ich sehen, was falsch läuft.

**Comment by emign** [comment]
Ach ich sehe was das Problem ist. Bintray scheint down zu sein: (Da werden die Libraries gehostet)
`Received status code 502 from server: Bad Gateway`

Da können wir nur abwarten

**Comment by emign** [comment]
Die Server sind wieder da. Durch die downtime haben sie sich ein paar mal verschluckt. Deshalb habe ich eine neue Version released. Bitte mit v0.55 weiter arbeiten
